---
- name: "Install ARM development packages"
  ansible.builtin.apt:
    name:
      - gcc-arm-none-eabi
      - binutils-arm-none-eabi
      - libnewlib-arm-none-eabi
      - libstdc++-arm-none-eabi-newlib
      - libusb-1.0-0-dev
      - dfu-util
      - dfu-programmer
      - openocd
    state: present

- name: "Create pico folder"
  become: false
  ansible.builtin.file:
    path: ~/pico
    state: directory
    mode: "0775"

- name: "Checkout Pico SDK repository"
  become: false
  ansible.builtin.git:
    repo: https://github.com/raspberrypi/pico-sdk.git
    dest: ~/pico/pico-sdk

- name: "Checkout Pico examples repository"
  become: false
  ansible.builtin.git:
    repo: https://github.com/raspberrypi/pico-examples.git
    dest: ~/pico/pico-examples

- name: "Checkout picotool repository"
  become: false
  ansible.builtin.git:
    repo: https://github.com/raspberrypi/picotool.git
    dest: ~/pico/picotool
