---
- name: Install basic packages
  ansible.builtin.apt:
    name:
      - vim
      - net-tools
      - tmux
      - screen
      - make
      - cmake
      - gcc
      - build-essential
      - git
      - tig
      - texlive-full
      - wget
      - curl
      - jq
    state: present

- name: Copy vim config
  become: false
  ansible.builtin.copy:
    src: config/vimrc
    dest: /home/{{ ansible_user }}/.vimrc
    mode: "0644"

- name: Copy tmux config
  become: false
  ansible.builtin.copy:
    src: config/tmux.conf
    dest: /home/{{ ansible_user }}/.tmux.conf
    mode: "0644"

- name: Copy git config
  become: false
  ansible.builtin.copy:
    src: config/gitconfig
    dest: /home/{{ ansible_user }}/.gitconfig
    mode: "0664"

- name: Copy tig config
  become: false
  ansible.builtin.copy:
    src: config/tigrc
    dest: /home/{{ ansible_user }}/.tigrc
    mode: "0664"

- name: Fix diff-highlight permissions (add +x)
  ansible.builtin.file:
    path: /usr/share/doc/git/contrib/diff-highlight/diff-highlight
    mode: "0755"

- name: Add GitHub CLI repository
  ansible.builtin.deb822_repository:
    name: github-cli
    types: deb
    architectures: amd64
    uris: https://cli.github.com/packages
    signed_by: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    suites: stable
    components: main
    state: present

- name: Install GitHub CLI
  ansible.builtin.apt:
    name: gh
    state: present

- name: Configure Git status
  become: false
  ansible.builtin.blockinfile:
    path: /home/{{ ansible_user }}/.bashrc
    insertbefore: '\$color_prompt'
    append_newline: true
    prepend_newline: true
    block: |
      GIT_PS1_SHOWDIRTYSTATE='y'
      GIT_PS1_SHOWSTASHSTATE='y'
      GIT_PS1_SHOWUNTRACKEDFILES='y'
      GIT_PS1_SHOWUPSTREAM='auto verbose'
      GIT_PS1_SHOWCONFLICTSTATE='yes'
      GIT_PS1_DESCRIBE_STYLE='contains'
      GIT_PS1_SHOWCOLORHINTS='y'

- name: Insert Git status to bash prompt
  become: false
  ansible.builtin.replace:
    path: /home/{{ ansible_user }}/.bashrc
    regexp: '(?<!\$\(__git_ps1\))\\\$ '''
    replace: '$(__git_ps1)\$ '''

- name: Start ssh-agent automatically
  become: false
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_user }}/.bashrc
    regexp: 'ssh-agent'
    line: 'eval "$(ssh-agent -s)" &>/dev/null'
