---
- name: "Add TLP repository from PPA"
  ansible.builtin.apt_repository:
    repo: ppa:linrunner/tlp
    state: present

- name: "Install battery packages"
  ansible.builtin.apt:
    name:
      - tlp
      - tlp-rdw
    state: present
