---
- name: Add Google Chrome signing key
  ansible.builtin.apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub

- name: Add Google Chrome repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    state: present

- name: Install Google Chrome
  ansible.builtin.apt:
    name: google-chrome-stable
    state: present
