---
- name: Add Google Chrome repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    state: present

- name: Install Google Chrome
  ansible.builtin.apt:
    name: google-chrome-stable
    state: present
