---
- name: Copy Openterface udev rules
  ansible.builtin.copy:
    src: udev/openterface.rules
    dest: /etc/udev/rules.d/51-openterface.rules
    mode: "0644"
  notify: Reload udev

- name: Add user to the dialout group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: dialout
    append: true

- name: Check latest Openterface_QT release
  ansible.builtin.uri:
    url: https://api.github.com/repos/TechxArtisanStudio/Openterface_QT/releases/latest
  register: openterface_latest
  check_mode: false

- name: Install Openterface_QT
  become: false
  ansible.builtin.get_url:
    url: "{{ openterface_latest.json | community.general.json_query(url_query) | join('') }}"
    dest: /home/{{ ansible_user }}/bin/openterfaceQT.AppImage
    mode: "0775"
  vars:
    url_query: assets[?contains(name,'amd64.AppImage')].browser_download_url
