---
- name: Add Hashicorp repository
  ansible.builtin.deb822_repository:
    name: hashicorp
    types: deb
    architectures: amd64
    uris: https://apt.releases.hashicorp.com
    signed_by: https://apt.releases.hashicorp.com/gpg
    suites: "{{ ansible_distribution_release }}"
    components: main
    state: present

- name: Install virtual machine packages
  ansible.builtin.apt:
    name:
      - virtualbox
      - vagrant
    state: present
