---
- name: Add Hashicorp repository
  ansible.builtin.deb822_repository:
    name: hashicorp
    types: deb
    architectures: amd64
    uris: https://apt.releases.hashicorp.com
    signed_by: https://apt.releases.hashicorp.com/gpg
    suites: "{{ ansible_distribution_release }}"
    components: main
    state: present

- name: Install virtual machine packages
  ansible.builtin.apt:
    name:
      - virtualbox
      - vagrant
    state: present

- name: Check if Vagrant autocomplete is installed
  become: false
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_user }}/.bashrc
    regexp: 'vagrant.*completion'
    state: absent
  check_mode: true
  changed_when: false
  register: vagrant_autocomplete_installed

- name: Install Vagrant autocomplete
  become: false
  ansible.builtin.command:
    cmd: vagrant autocomplete install --bash
  register: vagrant_autocomplete_install
  changed_when: vagrant_autocomplete_install.rc != 0
  when: not vagrant_autocomplete_installed.found
