---
- name: Add VS Code repository
  ansible.builtin.deb822_repository:
    name: vscode
    types: [deb]
    architectures: [amd64]
    uris: [https://packages.microsoft.com/repos/code]
    suites: [stable]
    components: [main]
    signed_by: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Install VS Code package
  ansible.builtin.apt:
    name: code
    state: present
