---
- name: Add Microsoft signing key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /usr/share/keyrings/microsoft.gpg

- name: Add VS Code repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64,arm64,armhf signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/code stable main
    state: present

- name: Install VS Code package
  ansible.builtin.apt:
    name: code
    state: present
