---
- name: Install window manager packages
  ansible.builtin.apt:
    name: i3
    state: present

- name: Create i3 config folder
  become: false
  ansible.builtin.file:
    path: ~/.config/i3/
    state: directory
    mode: "0775"

- name: Create i3status config folder
  become: false
  ansible.builtin.file:
    path: ~/.config/i3status/
    state: directory
    mode: "0775"

- name: Copy i3 config
  become: false
  ansible.builtin.copy:
    src: config/i3-config
    dest: ~/.config/i3/config
    mode: "0664"

- name: Copy i3status config
  become: false
  ansible.builtin.copy:
    src: config/i3status-config
    dest: ~/.config/i3status/config
    mode: "0644"
